# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.3
language: objective-c
jobs:
  include:
    - stage: Testing
      before_install:
        - gem install cocoapods
      script: 
        - cd Example
        - pod install
        - xcodebuild test -workspace Localizr-iOS.xcworkspace -scheme Localizr-iOS-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X' -quiet
    # - stage: Swift Package Manager
    #   script:
    #     - swift build
    - stage: deploying to cocoapods
      before_install:
        - echo $TRAVIS_TAG
        - export LOCALIZR_VERSION=$TRAVIS_TAG
        - gem install cocoapods
      script:
        - pod lib lint --allow-warnings
        - pod trunk push --allow-warnings
      if: tag IS present